run:
  timeout: 10m

linters:
  presets:
  - bugs

  enable:
  - bodyclose
  - gofmt
  - goimports
  - gosec
  - misspell
  - revive
  - unconvert
  - unparam

  disable:
  - scopelint # deprecated but still enabled in the bugs preset

linters-settings:
  misspell:
    locale: US
  gofmt:
    simplify: true
  unparam:
    check-exported: false
  goimports:
    local-prefixes: github.com/solo-io/go-control-plane-fork-v2
  exhaustive:
    default-signifies-exhaustive: true

issues:
  fix: true
